Controllers/DecryptController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kursach2.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Kursach2.Controllers
{
    public class DecryptController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddMessage(string key, string message, IFormFile uploadFile)
        {
            if (uploadFile != null && message != null)
            {
                return View("ErrorResult", "Отправлено сразу два поля");
            }
            if (uploadFile == null && message == null)
            {
                return View("ErrorResult", "Отправленные поля оказались пустыми");
            }

            MessageModel model = new MessageModel();
            if (uploadFile != null)
            {
                string type = uploadFile.FileName.Split('.')[1];
                if (!(type != "txt" || type != "docx"))
                {
                    return View("ErrorResult", "Отправлен неверный формат файла");
                }
                string path = "wwwroot/Files/" + uploadFile.FileName;
                using (var filestream = new FileStream(path, FileMode.OpenOrCreate))
                {
                    await uploadFile.CopyToAsync(filestream);
                }
                model.Key = key;
                model.PathFile = path;
                model.Parse(type);
            }
            else if (message != null)
            {
                model.Key = key;
                model.FirstMessage = message;
            }
            model.Decrypt();
            return View("Result", model);
        }
    }
}

Controllers/EncryptController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kursach2.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Kursach2.Controllers
{
    public class EncryptController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddMessage(string key, string message, IFormFile uploadFile)
        {
            if (uploadFile != null && message != null)
            {
                return View("ErrorResult", "Отправлено сразу два поля");
            }
            if (uploadFile == null && message == null)
            {
                return View("ErrorResult", "Отправленные поля оказались пустыми");
            }

            MessageModel model = new MessageModel();
            if (uploadFile != null)
            {
                string type = uploadFile.FileName.Split('.')[1];
                if (!(type != "txt" || type != "docx"))
                {
                    return View("ErrorResult", "Отправлен неверный формат файла");
                }
                string path = "wwwroot/Files/" + uploadFile.FileName;
                using (var filestream = new FileStream(path, FileMode.OpenOrCreate))
                {
                    await uploadFile.CopyToAsync(filestream);
                }
                model.Key = key;
                model.PathFile = path;
                model.Parse(type);
            }
            else if (message != null)
            {
                model.Key = key;
                model.FirstMessage = message;
            }
            model.Encrypt();
            return View("Result", model);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Kursach2.Models;
using Microsoft.AspNetCore.Http;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace Kursach2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Encrypt()
        {
            return View();
        }
        public IActionResult Decrypt()
        {
            return View();
        }
        
        
        [HttpGet]
        public FileResult GetTxtFileResult(string message)
        {
            System.IO.File.WriteAllText("wwwroot/Files/out.txt", message);
            byte[] buff = System.IO.File.ReadAllBytes("wwwroot/Files/out.txt");
            System.IO.File.Delete("wwwroot/Files/out.txt");
            return File(buff, "text/plain", "Result.txt");
        }
        [HttpGet]
        public FileResult GetDocxFileResult(string message)
        {
            string path = "wwwroot/Files/out.docx";
            string[] messageArr = message.Split('\n');
            using (var doc = WordprocessingDocument.Create(path, DocumentFormat.OpenXml.WordprocessingDocumentType.Document))
            {
                MainDocumentPart mainDocument = doc.AddMainDocumentPart();
                mainDocument.Document = new Document();
                Body body = mainDocument.Document.AppendChild(new Body());
                foreach (var par in messageArr)
                {
                    var para = body.AppendChild(new Paragraph());
                    var run = para.AppendChild(new Run());
                    run.AppendChild(new Text(par));
                }
            }
            byte[] buff = System.IO.File.ReadAllBytes(path);
            System.IO.File.Delete(path);
            return File(buff, "application/octet-stream", "Result.docx");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

Views/Home/Decrypt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Расшифровать";
}
<h1>Расшифровать</h1>
<form asp-action="AddMessage" asp-controller="Decrypt" method="post" enctype="multipart/form-data">
    <p>
        <b>Ключ:</b> <br />
        <input type="text" name="key" required/>
    </p>
    <h2>Ввести текст вручную</h2>
    <p>
        <b>Текст, который необходимо расшифровать:</b> <br />
        <textarea name="message" rows="10" cols="100"></textarea>
    </p>
    <h2>Или вы можете загрузить файл с текстом <b>(только .txt или .docx)</b></h2>
    <p>
        <b>Файл</b><br />
        <input type="file" name="uploadFile" typ/>
    </p>
    <input type="submit" value="Расшифровать" />
</form>

Views/Home/Encrypt.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Зашифровать";
}
<h1>Зашифровать</h1>
<form asp-action="AddMessage" asp-controller="Encrypt" method="post" enctype="multipart/form-data">
    <p>
        <b>Ключ:</b> <br />
        <input type="text" name="key" required />
    </p>
    <h2>Ввести текст вручную</h2>
    <p>
        <b>Текст, который необходимо зашифровать:</b> <br />
        <textarea name="message" rows="10" cols="100"></textarea>
    </p>
    <h2>Или вы можете загрузить файл с текстом <b>(только .txt или .docx)</b></h2>
    <p>
        <b>Файл</b><br />
        <input type="file" name="uploadFile" typ />
    </p>
    <input type="submit" value="Зашифровать" />
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать!</h1>
    <p>Здесь Вы можете <a asp-controller="Home" asp-action="Encrypt">Зашифровать</a> или <a asp-controller="Home" asp-action="Decrypt">Расшифровать</a> свое сообщение</p>
</div>